# Generated by Django 3.0.2 on 2020-01-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicofficial',
            name='positions',
            field=models.ManyToManyField(to='officials.Position'),
        ),
    ]
