# Generated by Django 3.0.2 on 2020-01-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_auto_20200123_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subagency',
            old_name='SAppointee',
            new_name='SAAppointee',
        ),
        migrations.RenameField(
            model_name='subagency',
            old_name='SAuthority',
            new_name='SAAuthority',
        ),
    ]
