# Generated by Django 3.0.2 on 2020-01-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_publicofficial_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.Agency')),
                ('subagency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.SubAgency')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='position_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='officials.PositionType'),
        ),
    ]
