# Generated by Django 3.0.2 on 2020-01-27 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_auto_20200127_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiontype',
            name='subagency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.SubAgency'),
        ),
    ]
