# Generated by Django 3.0.2 on 2020-01-23 22:58

from django.db import migrations
import officials.models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_auto_20200123_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subagency',
            name='SANeedsConf',
            field=officials.models.CFBNullBooleanField(),
        ),
    ]
