# Generated by Django 3.0.2 on 2020-01-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0004_auto_20200127_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicofficial',
            name='position_types',
            field=models.ManyToManyField(to='officials.PositionType'),
        ),
    ]
